name: Flutter Build

on:
  push:
    branches:
      - "*"
      - "!badges"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    #          - macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.5"
          channel: "stable"

      - name: Installation paquets
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build Application
        id: "flutter-build"
        continue-on-error: true
        shell: bash
        #if: runner.os == 'ubuntu'
        run: |
          label="flutter-build"
          echo "##[set-output name=label;]${label}"
          cd applicationcompte && flutter config --enable-linux-desktop && flutter build linux
          res=$?
          if [ $res -eq 0 ]
          then
            retour="passing"
            color="green"
          else
            retour="failing"
            color="red"
          fi
          echo "##[set-output name=status;]${retour}"
          echo "##[set-output name=color;]${color}"

      # switch to badges branch
      - run: |
          git checkout badge_flutter || git checkout -b badge_flutter
          test -d .github/badges || mkdir -p .github/badges

      # create badge
      - name: badge
        uses: emibcn/badge-action@v1.2.1
        with:
          label: ${{ steps.flutter-build.outputs.label }}
          status: ${{ steps.flutter-build.outputs.status || 'failing' }}
          color: ${{ steps.flutter-build.outputs.color || 'red' }}
          path: ".github/badges/badge_flutter.svg"

      # commit and push badges if badges have changed
      - name: Commit changes to badge
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add '.github/badges/badge_flutter.svg'
          git commit -m "Add/Update badge_flutter" || exit 0
          git push -f origin badge_flutter
